import Link from "next/link";
import report from "@/content/reports/smartphone-sales-in-spain/en/report.json";
import { ReportCta, ReportFindings, ReportMetadata, ReportNote, ReportSources, ReportTableOfContents, ReportTextSection } from "@/components/reports/full-report-primitives";

const reportPath = "/en/sample-reports/smartphone-sales-in-spain";
const downloadPath = "/en/downloads/reports/smartphone-sales-in-spain";
const sectionTitles = ["Executive Summary", "Market Overview", "Competitive Landscape", "Pricing & Distribution", "Regulatory Environment", "Consumer Trends", "Key Opportunities", "Risks & Challenges"] as const;

function reflow(value: string) {
  return value.replace(/\r/g, "").replace(/\f/g, "\n").replace(/-\n\s*/g, "-").replace(/\n\s*/g, " ").replace(/\s{2,}/g, " ").trim();
}

function between(text: string, start: string, end?: string) {
  const startIndex = text.indexOf(start);
  if (startIndex < 0) return "";
  const from = startIndex + start.length;
  const endIndex = end ? text.indexOf(end, from) : -1;
  return text.slice(from, endIndex >= 0 ? endIndex : undefined).trim();
}

const raw = report.content.replace(/\r/g, "").replace(/\f/g, "");
const titleInSource = "Smartphone Sales in Spain: Market Profile\nand Competitive Dynamics";
const introduction = reflow(between(raw, titleInSource, "GEOGRAPHY"));
const findings = between(raw, "KEY FINDINGS", "Executive Summary").split(/\n\s*(?=(?:Spain\x27s|The 2024|Xiaomi|Value-for-money|Repair and|Adjacent))/).map(reflow).filter(Boolean);
const sections = sectionTitles.map((title, index) => ({
  id: title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, ""),
  title,
  paragraphs: between(raw, title, sectionTitles[index + 1] ?? "Sources (156 total)").split(/\n\s*\n/).map(reflow).filter(Boolean),
}));
const sourceText = between(raw, "Sources (156 total)", "Research limitations:").trim();
const limitationText = between(raw, "Research limitations:", "Generated by Tavily Web Research Agent");
const limitations = limitationText.split(/(?<=\.)\n\s*(?=[A-Z])/).map(reflow).filter(Boolean);
const generatedBy = reflow(between(raw, "Generated by Tavily Web Research Agent"));
const contents = [
  { id: "key-findings", title: "Key Findings" },
  ...sections.map(({ id, title }) => ({ id, title })),
  { id: "methodology", title: "Methodology" },
  { id: "limitations", title: "Research limitations" },
  { id: "sources", title: "Sources (156 total)" },
];

export function SpainSmartphoneReport() {
  return <section aria-labelledby="full-report-title" className="border-t border-line bg-surface py-12 md:py-20">
    <div className="mx-auto w-full max-w-6xl px-6 md:px-8">
      <article className="mx-auto max-w-4xl">
        <header className="border-b border-line pb-8 md:pb-10">
          <p className="eyebrow">FREE {"\u00B7"} ENGLISH</p>
          <h1 id="full-report-title" className="mt-4 max-w-3xl text-display-lg text-brand-primary">{report.title}</h1>
          <p className="mt-5 max-w-3xl text-lg leading-8 text-body-secondary">{introduction}</p>
          <nav aria-label="Report formats" className="mt-7 grid grid-cols-2 gap-3 sm:flex sm:flex-wrap">
            <Link href={reportPath} className="button-primary w-full sm:w-auto">Read HTML</Link>
            <a href={report.pdf_path} download className="button-secondary w-full sm:w-auto">Download PDF</a>
            <Link href={`${downloadPath}/markdown`} download className="button-secondary w-full sm:w-auto">Download Markdown</Link>
            <Link href={`${downloadPath}/json`} download className="button-secondary w-full sm:w-auto">Download JSON</Link>
          </nav>
        </header>

        <ReportMetadata items={[
          { label: "Geography", value: "Spain" },
          { label: "Industry", value: "market research" },
          { label: "Sources", value: "156 (91 high credibility)" },
          { label: "Date", value: "July 14, 2026" },
        ]} />

        <ReportTableOfContents items={contents} />
        <ReportFindings findings={findings} />

        <div className="mt-12">{sections.map((section) => <ReportTextSection key={section.id} {...section} />)}</div>

        <div className="grid gap-6 py-10 lg:grid-cols-2">
          <ReportNote id="methodology" title="Methodology"><p>Source: Tavily Open Web Discovery</p></ReportNote>
          <ReportNote id="limitations" title="Research limitations"><ul className="grid gap-4 text-sm leading-7">{limitations.map((limitation) => <li key={limitation} className="ml-5 list-disc pl-1">{limitation}</li>)}</ul></ReportNote>
        </div>

        <ReportSources sourceText={sourceText} />
        <p className="text-sm text-muted">Generated by Tavily Web Research Agent{generatedBy ? ` ${generatedBy}` : ""}</p>

        <ReportCta>
          <div><h2 className="text-display-xs text-brand-primary">Need a tailored answer?</h2><p className="mt-3 max-w-2xl text-body-secondary">Discuss a custom market research report or ongoing intelligence support with ASB Market Research.</p></div>
          <Link href="/en/quotation" className="button-primary mt-6 md:mt-0">Request custom research</Link>
        </ReportCta>
      </article>
    </div>
  </section>;
}